eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      RatingBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
